### PR TITLE
add withdraw-circuit functionality & fix getFeeIndex

### LINKED ISSUE #98: Fee index computation
Investigate fee index computation since it returns unexpected values

### LINKED ISSUE #99: Withdraw circuit implementation
Add support for `withdrawCircuit` functionaility

### PR DESCRIPTION
**Pull request by krlosMata**
This PR implements the following:
- adds `withdrawCircuit` functionality
  - implemented in `tx.js` 
  - added files `wasm` & `zkey` to compute zkProof
  - added `withdraw-utils.js`
- fix fee index computation
  - `getFeeIndex` returns 0 if fee selected is 0 

close #99
close #98

### CODE REVIEW

File: src/withdraw-utils.js [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+/**
+ * Build zkProof valid for the verifier contract
+ * @param {Object} proofSnarkjs - Proof received from snarkjs package
+ * @returns {Object} - zkProof ready for contract parameter
+ */
+async function buildProofContract (proofSnarkjs) {
+  const proofContract = {}
+
+  proofContract.proofA = [
+    proofSnarkjs.pi_a[0],
```
Comment (AlbertoElias) [inline src/withdraw-utils.js:40]: does pi_a have more than 2 values? If not you could use spread `proofContract.proofA = [...proofSnarkjs.pi_a]`

File: tests/tx.test.js [hunk 2]
```diff
@@ -339,6 +314,51 @@ describe('Full flow', () => {
     expect(Scalar.gt(newBalance, oldBalance)).toEqual(true)
   })
 
+  test('Exit and circuit withdrawal', async () => {
+    const oldBalance = Scalar.e(await provider.getBalance(getEthereumAddress(
+      accounts[0].hermezWallet.hermezEthereumAddress)))
```
Comment (AlbertoElias) [inline tests/tx.test.js:319]: For style purposes, I would put the last 2 )) in a new line

File: tests/withdraw-utils.test.js [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+        '19751761238788082485485782295592147387853195509253232129476034439772029001653',
+        '3635016281318032270391337149678584018489690690880370006504444187549384347948',
+        '1'
+      ],
+      protocol: 'groth16'
+    }
+
+    const proofContract = await withdrawUtils.buildProofContract(proofSnarkjs)
+
+    expect(proofContract.proofA).not.toBe(undefined)
```
Comment (AlbertoElias) [inline tests/withdraw-utils.test.js:38]: Couldn't you check the exact value?

**Review by AlbertoElias — APPROVED** [review]
A few small comments

File: src/tx.js [hunk 4]
```diff
@@ -200,6 +202,53 @@ const withdraw = async (
...
+ * @param {String} providerUrl - Network url (i.e, http://localhost:8545). Optional
+ * @param {Number} gasLimit - Optional gas limit
+ * @param {Number} gasMultiplier - Optional gas multiplier
+ * @returns {Promise} transaction parameters
+ * @throws {Error} Throws an error if account index isn't valid
+ */
+const withdrawCircuit = async (
+  exitInfo,
+  isInstant = true,
+  wasmFilePath,
```
[the remark this answers is not in the document]
Comment (krlosMata) [reply src/tx.js:221]: The value in constants are the links to the files. It must be updated after this merge.
Those files would not be included in npm package, then in order to use them they should be downloaded first with `wget https://...` and I would no set it as default behavior in the library

File: src/withdraw-utils.js (hunk 1 above)
Comment (krlosMata) [reply src/withdraw-utils.js:40]: yes, `snarkjs` output has 3 values

File: tests/withdraw-utils.test.js (hunk 3 above)
Comment (krlosMata) [reply tests/withdraw-utils.test.js:38]: yes, I will change it :)

File: package.json [hunk 5]
```diff
@@ -24,6 +24,7 @@
     "prebuild": "rm -rf dist",
     "build-publish": "npm run build-node && npm publish",
     "test": "jest",
+    "test:int": "jest --forceExit --detectOpenHandles",
```
Comment (elias-garcia) [inline package.json:27]: Do we really need this test npm script or it was just for testing purposes for this PR?

**Review by elias-garcia — APPROVED** [review]

File: package.json (hunk 5 above)
Comment (krlosMata) [reply package.json:27]: it is needed in case `tx.test.js` is run. Since `withdrawCircuit` functionality is added, zk-proof is computed in background with `snarkjs` and jest does not stop processes unless this flag options are set.

File: src/tx.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (krlosMata) [reply src/tx.js:220]: change it to get wasm-xkey files from url when it is run on browser

**Review by AlbertoElias — APPROVED** [review]
